version: '2'
services:
    life-science-blast:
        image: local-dtr.zhihuiya.com/lifescience/blast
        build: .
        environment:
            - BLASTDB=/patsnap/blastdb
            - redisHost=192.168.3.89
        volumes:
            - ~/work/patsnap/blastdb:/patsnap/blastdb
        ports:
           - 3001:3000
        container_name: life-science-blast

