/**
 * Created by shawn-liu on 17/9/22.
 */
const blastjs = require('../../../src/lib/blastjs');
const fs = require('fs');
const db = 'refseq_rna.00 ';
const query = 'GGGAGCTTCCGGATTGAGCCGGAAGTCCCCCCAGAGCGGATGCCGCGGCGGGCCTGTGGGAGCGGGGTCATCTTCTCTCTGCTGCTGTAGCTGCCATGGGCAAAAGAGACCGAGCGGACCGCGACAAGAAGAAATCCAGGAAGCGGCACTATGAGGATGAAGAGGATGATGAAGAGGACGCCCCGGGGAACGACCCTCAGGAAGCGGTTCCCTCGGCGGCGGGGAAGCAGGTGGATGAGTCAGGCACCAAAGTGGATGAATATGGAGCCAAGGACTACAGGCTGCAAATGCCGCTGAAGGACGACCACACCTCCAGGCCCCTCTGGGTGGCTCCCGATGGCCATATCTTCTTGGAAGCCTTCTCTCCAGTTTACAAATATGCCCAAGACTTCTTGGTGGCTATTGCAGAGCCAGTGTGCCGACCAACCCATGTGCATGAGTACAAACTAACTGCCTACTCCTTGTATGCAGCTGTCAGCG';
(async () => {
    try {
        const fileData = fs.readFileSync('./query.fa','utf8');
        const query1 = fileData.toString();
        const response = await blastjs.blastN(db, query1);
        console.log(response);
    } catch (err) {
        console.error(err);
    }
})();
